config/routes.rb
Administration::Engine.routes.draw do  
  resources :article_types, :article_categories, :article_cluster_categories, :members, :publications, :admins, :pages

  resources :blogs do
    resources :blog_comments
  end

  get "landing/index"
  root "landing#index"
end

app/models/administration/admin.rb
module Administration
  class Admin < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]

    # Non-devise field validations

    validates :first_name, presence: true, length: { maximum: 20 }
    validates :last_name, presence: true, length: { maximum: 20 }
  end
end

app/models/administration/blog.rb
module Administration
  class Blog
    include Mongoid::Document
    include Mongoid::Timestamps

    embeds_many :blog_comments, :class_name => "Administration::BlogComment"

    before_save :sanitize_text
    before_update :sanitize_text

    field :title, type: String
    field :content, type: String
    field :author, type: Integer
    field :published, type: Boolean, default: false

    validates_presence_of :title, :content
    validates :title, length: {maximum: 255}

    def sanitize_text
      self[:content] = CommonDomain::InputSanitizer.new.sanitize_this(self[:content])
    end
  end
end

app/controllers/administration/admins_controller.rb
require_dependency "administration/application_controller"

module Administration
  class AdminsController < ApplicationController
    def index
      @admins = Administration::Admin.all.order("created_at DESC").page(params[:page]).per(10)
    end

    def show
      @admin = Administration::Admin.find(params[:id])
    end

    def new
      @admin = Administration::Admin.new
      variables_for_new
    end

    def create
      @admin = Administration::Admin.new(admin_params)

      if @admin.save
        redirect_to administration.admins_path, :notice => "A new type was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the type was not saved"
      end
    end

    def edit
      @admin = Administration::Admin.find(params[:id])
      variables_for_edit
    end

    def update
      @admin = Administration::Admin.find(params[:id])

      if @admin.update_attributes(admin_params)
        redirect_to administration.admins_path, notice: 'An admin was successfully updated.'
      else
        variables_for_edit
        render action: :edit, notice: "Update failed, please try again"
      end
    end

    def destroy
      @admin = Administration::Admin.find(params[:id])
    
      unless @admin.destroy
        redirect_to(administration.admins_path, notice: "An error occured, the deletion was not successful")
      else
        redirect_to(administration.admins_path, notice: "An admin's account was deleted")
      end
    end

    private
    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :email, :password)
    end

    # these variables are required whenever the new view is rendered
    def variables_for_new
      @path = administration.admins_path
      @method = :post
    end

    # these variables are required whenever the edit view is rendered
    def variables_for_edit
      @path = administration.admin_path
      @method = :patch
    end
  end
end

app/controllers/administration/application_controller.rb
module Administration
  class Administration::ApplicationController < ::ApplicationController
    before_filter :authenticate_admin!
  end
end

app/controllers/administration/article_categories_controller.rb
require_dependency "administration/application_controller"

module Administration
  class ArticleCategoriesController < ApplicationController
    # Require this in order to avoid uninitialized constant
    require "#{Article::Engine.root}/app/models/article/publication.rb"

    def index
      @categories = Article::Category.all.reverse
    end

    def new
      @category = Article::Category.new
      variables_for_new
    end

    def create
      @category = Article::Category.new(category_params)

      if @category.save
        redirect_to administration.article_categories_path, :notice => "A new category was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the category was not saved"
      end
    end

    def edit
      @category = Article::Category.find(params[:id])
      variables_for_edit
    end

    def update
      @category = Article::Category.find(params[:id])

      if @category.update_attributes(category_params)
        redirect_to administration.article_categories_path, notice: 'Successfully updated.'
      else
        variables_for_edit
        render action: :edit, :notice => "An error occured, the category was not saved"
      end
    end

    private

    def category_params
      params.require(:category).permit(:title, :description)
    end

    # these variables are required whenever the new view is rendered
    def variables_for_new
      @path = administration.article_categories_path
      @method = :post
    end

    # these variables are required whenever the edit view is rendered
    def variables_for_edit
      @path = administration.article_category_path
      @method = :patch
    end
  end
end

app/controllers/administration/article_cluster_categories_controller.rb
require_dependency "administration/application_controller"

module Administration
  class ArticleClusterCategoriesController < ApplicationController
    # Require this in order to avoid uninitialized constant
    require "#{Article::Engine.root}/app/models/article/publication.rb"

    def index
      @clusters = Article::ClusterCategory.all.reverse
    end

    def new
      @cluster = Article::ClusterCategory.new
      variables_for_new
    end

    def create
      @cluster = Article::ClusterCategory.new(cluster_category_params)

      if @cluster.save
        redirect_to administration.article_cluster_categories_path, :notice => "A new cluster category was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the  cluster category was not saved"
      end
    end

    def edit
      @cluster = Article::ClusterCategory.find(params[:id])
      variables_for_edit
    end

    def update
      @cluster = Article::ClusterCategory.find(params[:id])

      if @cluster.update_attributes!(cluster_category_params)
        redirect_to administration.article_cluster_categories_path, notice: 'Successfully updated cluster category.'
      else
        variables_for_edit
        render action: :edit, :notice => "An error occured, the cluster category was not saved"
      end
    end

    private

    def cluster_category_params
      params.require(:cluster_category).permit(:title, :description)
    end

    # these variables are required whenever the new view is rendered
    def variables_for_new
      @path = administration.article_cluster_categories_path
      @method = :post
    end

    # these variables are required whenever the edit view is rendered
    def variables_for_edit
      @path = administration.article_cluster_category_path
      @method = :patch
    end
  end
end

app/controllers/administration/article_types_controller.rb
require_dependency "administration/application_controller"

module Administration
  class ArticleTypesController < ApplicationController
    # Require this in order to avoid uninitialized constant
    require "#{Article::Engine.root}/app/models/article/publication.rb"

    def index
      @types = Article::Type.all.reverse
    end

    def new
      @type = Article::Type.new
      variables_for_new
    end

    def create
      @type = Article::Type.new(type_params)

      if @type.save
        redirect_to administration.article_types_path, :notice => "A new type was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the type was not saved"
      end
    end

    def edit
      @type = Article::Type.find(params[:id])
      variables_for_edit
    end

    def update
      @type = Article::Type.find(params[:id])

      if @type.update_attributes(type_params)
        redirect_to administration.article_types_path, notice: 'Successfully updated.'
      else
        variables_for_edit
        render action: :edit, :notice => "An error occured, the type was not saved"
      end
    end

    def destroy
      @type = Article::Type.find(params[:id])
    
      unless @type.destroy
        redirect_to(administration.article_types_path, notice: "An error occured, the deletion was not successful")
      else
        redirect_to(administration.article_types_path, notice: "A article type was deleted")
      end
    end

    private

    def type_params
      params.require(:type).permit(:title, :description)
    end

    # these variables are required whenever the new view is rendered
    def variables_for_new
      @path = administration.article_types_path
      @method = :post
    end

    # these variables are required whenever the edit view is rendered
    def variables_for_edit
      @path = administration.article_type_path
      @method = :patch
    end
  end
end

app/controllers/administration/blog_comments_controller.rb
require_dependency "administration/application_controller"

module Administration
	class BlogCommentsController < ApplicationController
    skip_before_filter :authenticate_admin!, only: [:create]

		def create
      @blog = Blog.find(params[:blog_id])

      if admin_signed_in? && !user_signed_in?
        params[:blog_comment][:author] = current_admin.id
        params[:blog_comment][:admin] = true
      else
        params[:blog_comment][:author] = current_user.id
        params[:blog_comment][:admin] = false
      end

      comment = @blog.blog_comments.create!(comment_params)

      redirect_to @blog
    end

    def destroy
    end

    private
    def comment_params
      allow = [:content, :admin, :author]
      params.require(:blog_comment).permit(allow)
    end
  end
end

app/controllers/administration/blogs_controller.rb
require_dependency "administration/application_controller"

module Administration
  class BlogsController < ApplicationController
    
    def index
      @blogs =  Administration::Blog.all.order("created_at ASC").page(params[:page]).per(5)
    end

    def show
      @blog = Administration::Blog.find(params[:id])
    end

    def edit
      @blog = Administration::Blog.find(params[:id])
    end

    def new
      @blog = Administration::Blog.new
    end

    def create
      @blog =  Administration::Blog.new(blog_params)
      @blog.author =  current_admin.id
      
      if @blog.save
        redirect_to administration.blogs_path, :notice => "A new post was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the type was not saved"
      end
    end

    def update 
      @blog = Administration::Blog.find(params[:id])
      @blog.author =  current_admin.id

      if @blog.update_attributes(blog_params)
        redirect_to @blog, notice: 'Post was successfully updated.'
      else
        render action: :edit, notice: "Update failed, please try again"
      end
    end

    def destroy
      @blog = Blog.find(params[:id])
      @blog.destroy

      redirect_to blogs_path
    end

    private
    def blog_params
      allow = [:title, :content, :author, :published]
      params.require(:blog).permit(allow)
    end
  end
end

app/controllers/administration/landing_controller.rb
require_dependency "administration/application_controller"

module Administration
  class LandingController < ApplicationController
    def index
    	@publications = Article::Publication.limit(6)
    	@members = Member::User.limit(10)
    end
  end
end

app/controllers/administration/members_controller.rb
require_dependency "administration/application_controller"

module Administration
  class MembersController < ApplicationController
    def index
      @members = Member::User.all.order("created_at DESC").page(params[:page]).per(10)
    end

    def show
      @member = Member::User.find(params[:id])
      @publications = Article::Publication.where(author: params[:id]).order("created_at DESC").page(params[:page]).per(10)
    end

    def new
      @user = Member::User.new
      variables_for_new
    end

    def create
      @user = Member::User.new(user_params)

      if @user.save
        redirect_to administration.members_path, :notice => "A new type was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the type was not saved"
      end
    end

    def edit
      @user = Member::User.find(params[:id])
      variables_for_edit
    end

    def update
      @user = Member::User.find(params[:id])

      if @user.update_attributes(user_params)
        redirect_to administration.members_path, notice: 'Member was successfully updated.'
      else
        variables_for_edit
        render action: :edit, notice: "Update failed, please try again"
      end
    end

    def destroy
      @member = Member::User.find(params[:id])
    
      unless @member.destroy
        redirect_to(administration.members_path, notice: "An error occured, the deletion was not successful")
      else
        redirect_to(administration.members_path, notice: "A member's account was deleted")
      end
    end

    private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :role)
    end

    # these variables are required whenever the new view is rendered
    def variables_for_new
      @path = administration.members_path
      @method = :post
    end

    # these variables are required whenever the edit view is rendered
    def variables_for_edit
      @path = administration.member_path
      @method = :patch
    end
  end
end

app/controllers/administration/pages_controller.rb
require_dependency "administration/application_controller"

module Administration
  class PagesController < ApplicationController

    def index
      @pages =  Administration::Page.all.order("created_at ASC").page(params[:page]).per(5)
    end

    def show
      @page = Administration::Page.find(params[:id])
    end

    def edit
      @page = Administration::Page.find(params[:id])
      variables_for_edit
    end

    def new
      @page = Administration::Page.new
    end

    def create
      @page = Administration::Page.new(page_params)
      
      if @page.save
        redirect_to administration.pages_path, :notice => "A new post was created!"
      else
        variables_for_new
        render action: :new, :notice => "An error occured, the type was not saved"
      end
    end

    def update 
      @page = Administration::Page.find(params[:id])

      if @page.update_attributes(page_params)
        redirect_to pages_path, notice: 'Post was successfully updated.'
      else
        render action: :edit, notice: "Update failed, please try again"
      end
    end

    def destroy
      @page = Page.find(params[:id])
      @page.destroy

      redirect_to pages_path
    end

    private
    def page_params
      allow = [:title, :content, :main]
      params.require(:page).permit(allow)
    end

    def variables_for_new
      @path = administration.pages_path
      @method = :post
    end

    def variables_for_edit
      @path = administration.page_path
      @method = :patch
    end
  end
end

app/controllers/administration/publications_controller.rb
require_dependency "administration/application_controller"

module Administration
  class PublicationsController < ApplicationController
    def index
      @publications = Article::Publication.all
    end

    def show
      @publication = Article::Publication.find(params[:id])
    end

    def edit
      @publication = Article::Publication.find(params[:id])
    end

    def update
      @publication = Article::Publication.find(params[:id])

      if @publication.update_attributes!(publication_params)
        redirect_to administration.publications_path, notice: 'Successfully updated'
      else
        render action: :edit, :notice => "An error occured, the article was not updated"
      end
    end

    def destroy
      @publication = Article::Publication.find(params[:id])
      @publication.destroy

      redirect_to administration.publications_path, notice: 'Successfully deleted an article'
    end

    private

    def publication_params
      params.require(:publication).permit(:title, :content, :published, :type_id, :category_id, :cluster_category_id)
    end
  end
end

app/helpers/administration/application_helper.rb
module Administration
  module ApplicationHelper
  end
end

app/helpers/administration/article_categories_helper.rb
module Administration
  module ArticleCategoriesHelper
  end
end

app/helpers/administration/article_types_helper.rb
module Administration
  module ArticleTypesHelper
  end
end

app/helpers/administration/blog_comments_helper.rb
module Administration
  module BlogCommentsHelper
  end
end

app/helpers/administration/blogs_helper.rb
module Administration
  module BlogsHelper
  end
end

app/views/administration/blogs/_form.html.erb
<%= tinymce_assets %>
<div class="composer">
  <%= form_for(@blog) do |f| %>
    <%= tinymce %>

    <% if @blog.errors.any? %>
      <div class="error_messages">
        <h3>Submission failed</h3>
        <ul>
          <% for message in @blog.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <br>
    <% end %>

    <div class="row-fluid overhead">
      <div class="span6">
        <%= f.text_field :title, :required => true, :placeholder=>"Title" %>
      </div>

      <div class="span6 check-style">
        <div class="option-box">
          <%= f.check_box :published %>
          <%= f.label :published %>
          <i>(Should it be visible to users?)</i>
        </div>
      </div>
    </div>

    <div>
      <%= f.text_area :content, :class => "tinymce", size: '100x20' %>
    </div>

    <div class="row-fluid overhead">
      <div class="span2">
        <%= f.submit "Save", :class=>"mock-btn" %>
      </div>
      <div class="span10"></div>
    </div>
</div>
<% end %>

app/views/administration/blogs/edit.html.erb
<div class="row-fluid">
  <div class="span9">
    <div class="admin-head">
     <h1>Edit <%= @blog.title %></h1>
   </div>
   <div class="blog-showcase">
     <%= render 'form' %>
   </div>
 </div>
 <div class="span3">
    <div class="admin-head hidden-phone">
      <h1>Administration</h1>
    </div>
    <div class="admin-info hidden-phone">
      <ul>
        <li><%= link_to 'Delete this blog', @blog, confirm: 'Are you sure?', :method => :delete %><br></li>
      </ul>
    </div>
    <div class="admin-info hidden-phone">
      <ul>
        <%= render :file => "#{Administration::Engine.root}/app/views/shared/_shortcuts.html.erb" %>
      </ul>
    </div>
  </div>
</div>

app/views/administration/blogs/index.html.erb
<div class="row-fluid">
  <%= render :file => "#{Administration::Engine.root}/app/views/shared/_adminaside.html.erb" %>

  <div class="span9">
    <div class="admin-head"><h3>Blogs</h3></div>
    <div class="overview">
      <%= link_to "New blog", administration.new_blog_path,:class=>"mock-btn" %>
      <div class="row-fluid">
        <% @blogs.each do |blog| %>
          <div class="index-list-style">
            <h3><%= link_to blog.title, blog %></h3>
            <span>Published on <%= blog.created_at.strftime("%d %b. %Y") %></span>
            <div class="structurise">
              <%= truncate_to_paragraph(blog.content) %>
            </div>
            <div class="blog-foot">
              <%= link_to "Read more", blog, :class=>"mock-btn"%>
              <%= link_to 'Edit', edit_blog_path(blog), :class=>"mock-btn" %>
              <%= link_to 'Delete', blog, confirm: 'Are you sure?', method: :delete, :class=>"mock-btn del" %>
            </div>
          </div>
        <% end %>
      </div>
      <%= paginate @blogs, :remote => false %>
    </div>
  </div>    
</div>

app/views/administration/blogs/new.html.erb
<div class="row-fluid">
  <div class="span9">
    <div class="admin-head">
     <h1>New post</h1>
   </div>
   <div class="blog-showcase">
     <%= render 'form' %>
   </div>
 </div>
 <div class="span3">
    <div class="admin-head hidden-phone">
      <h1>Administration</h1>
    </div>
    <div class="admin-info hidden-phone">
      <ul>
        <%= render :file => "#{Administration::Engine.root}/app/views/shared/_shortcuts.html.erb" %>
      </ul>
    </div>
  </div>
</div>

app/views/administration/blogs/show.html.erb
<div class="row-fluid">
  <div class="span9">
    <div class="admin-head">
      <h1><%= @blog.title %></h1>
      <div class="visible-phone">
        <i>Posted <%= @blog.created_at.strftime("%d %b. %Y") %></i>
      </div>
    </div>
    <div class="blog-showcase structurise">
      <%= simple_format @blog.content %>
      
      <% if admin_signed_in? || user_signed_in? %>
        <div class="admin-head">
          <h3>New comment</h3>
        </div>
        <%= form_for [@blog, Administration::BlogComment.new] do |f| %>
          <p><%= f.text_area :content, :rows => 10, :class=>"span12" %></p>
          <p><%= f.submit "Send", :class=>"mock-btn" %></p>
        <% end %>
      <% end %>
      
      <% if @blog.blog_comments.size > 0 %>
        <div class="blog-comments">

          <div class="admin-head">
            <h3>Comments</h3>
          </div>

          <% @blog.blog_comments.each do |comment| %>
            <div class="comment-post">
              <% if comment.admin %>
                <h3 style="color:#FC6E51;">Administrator</h3>
              <% else %>
                <b><%= find_author_name(comment.author) %></b>
              <% end %>

              <i><%= comment.created_at.strftime("%I:%M %d %b, %Y") %></i>

              <p><%= comment.content %></p>
            </div>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>

  <div class="span3">
    <div class="admin-head hidden-phone">
      <h1>Administration</h1>
    </div>
    <div class="admin-info hidden-phone">
      <ul>
        <li><%= link_to 'Edit this blog', administration.edit_blog_path(@blog) %></li>
        <li><%= link_to 'Delete this blog', @blog, confirm: 'Are you sure?', :method => :delete %><br></li>
      </ul>
    </div>
    <div class="admin-info hidden-phone">
      <ul>
        <%= render :file => "#{Administration::Engine.root}/app/views/shared/_shortcuts.html.erb" %>
      </ul>
    </div>
  </div>
</div>